---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      -
        name: Push image
        run: |
          docker build -t conorbros/hot-restart-proxy:latest -t conorbros/hot-restart-proxy:${GITHUB_REF/refs\/tags\//} .
          docker push conorbros/hot-restart-proxy:latest
          docker push conorbros/hot-restart-proxy:${GITHUB_REF/refs\/tags\//}
