---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"


jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build & test
        run: |
          #cargo build --release
          cargo build # just build debug while testing so it's quicker
      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files:
